Repository wecode-bootcamp-korea/16-2nd-market-ssua-backend, pull requests merged in 2021-02, with the labels that each got.

#5 [16기 김준형] 로그인, 소셜 로그인
  decorators/utils.py
  users/tests.py
  users/urls.py
  users/views.py
Labels: Status: 리뷰 요청

#8 [16기 최수아] Edit : ProductGroupListView
  market_ssua/urls.py
  products/tests.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#7 [16기 김준형] 장바구니 기능 추가
  Dockerfile
  decorators/utils.py
  market_ssua/settings.py
  market_ssua/urls.py
  orders/migrations/0001_initial.py
  orders/migrations/0002_auto_20210129_1402.py
  orders/migrations/0002_auto_20210202_1342.py
  orders/migrations/0003_merge_20210131_0128.py
  orders/models.py
  orders/tests.py
  orders/urls.py
  orders/views.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20210129_1402.py
  products/migrations/0002_auto_20210202_1342.py
  products/migrations/0003_productgroup_price.py
  products/migrations/0004_merge_20210131_0128.py
  products/models.py
  products/views.py
  requirements.txt
  users/migrations/0001_initial.py
  users/models.py
  users/tests.py
  users/views.py
Labels: Status: 리뷰 요청

#9 [16기 최수아] QuestionView
  orders/migrations/0001_initial.py
  orders/migrations/0002_auto_20210202_1426.py
  products/migrations/0001_initial.py
  products/migrations/0002_auto_20210202_1426.py
  products/tests.py
  products/urls.py
  products/views.py
  users/migrations/0001_initial.py
Labels: Status: Accepted

#10 [16기 김준형] 최종 수정본
  Dockerfile
  docker-compose.yml
  market_ssua/settings.py
  orders/urls.py
  orders/views.py
  products/views.py
  users/views.py
Labels: Status: 리뷰 진행중

#11 [16기 최수아] question view unit-test 수정
  products/tests.py
Labels: Status: 리뷰 요청

#12 [16기 김준형] social login 수정, product 수정
  orders/views.py
  products/views.py
  users/views.py
Labels: Status: Accepted
